#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Depaniko                                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Trouvez un artisan en quelques clics!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Thomas Guinot                               
your_link                                 : https://www.depaniko.com                     
your_city                                 :                                 
email_address                             : thomas.guinot@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : Depaniko/mobile-app
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Localisation GPS
    description                           : Avec Depaniko, trouvez des artisans et dépanneurs proches de chez vous et pouvant intervenir rapidement!
    fontawesome_icon_name                 : magic
    
  - title                                 : Réservations rapides
    description                           : Grâce aux appels vidéo et aux photos, vous pouvez décrire rapidement votre besoin, et expliquer clairement les travaux que vous souhaiter réaliser.
    fontawesome_icon_name                 : mobile

  - title                                 : Qualifications et certifications professionnelles
    description                           : Filtrez les artisans par qualifications ou certifications RGE et Qualibat directement depuis l'application!
    fontawesome_icon_name                 : play-circle

  - title                                 : Éxperience et avis 
    description                           : Selectionnez l'artisan qui vous convient le mieux grâce aux avis clients et aux photos détaillées de leurs travaux précedents!
    fontawesome_icon_name                 : sync

  - title                                 : Devis et factures automatiques
    description                           : Depaniko vous permet de générer, signer et télécharger vos devis & factures directement depuis l'application.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Pour les artisans, une garantie de paiement  
    description                           : Travaillez en toute quiétude grâce au système de paimenent Depaniko. Nous nous assurons de la disponibilité des fonds de vos futurs clients avant de valider leurs réservations.
    fontawesome_icon_name                 : star

  - title                                 : Pour les artisans, trouver des matériaux proches de soi!
    description                           : Depaniko vous offre la possibilité de trouver et d'acheter des matériaux et fournitures autour de votre localisation.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Pour les artisans, revendre son surplus
    description                           : Grâce a notre partenaire StockPro, revendez facilement votre surplus de matériel après chacun de vos travaux!
    fontawesome_icon_name                 : link




# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpeg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.6

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
